# @package _global_

defaults:
  - _self_
  - ../paths/paths_own
  - ../common

repo_root: ${repo_root}
processed_data_root: ${processed_data_root}
seq_num: ${seq_num}
output_dir: ${output_dir_gt_own}
vis: false
save_vis: true
single_frame: false

# --- generation parameters --- #

tf_id: 1  # currently unused
lidar_sensor: 0  # currently unused

# resolve the inherent ambiguity in normal vector orientation (vector from these will be [0, 0, 1])
cam_ref_pt: [0, 0, 1]  # camera reference point (0, 0, 1 in the LiDAR (tf_to_frist_frame) coordinate system)
plane_ctr_pt: [0, 0, 0] # plane center point (0, 0, 0 in the LiDAR (tf_to_frist_frame) coordinate system)

# --- common parameters --- #

img_src_size: ${img_src_size}
roi: ${roi}  # use roi: ${roi.0} to select the first ROI dynamically

# --- coordinate frames --- #

# camera:  ??? e.g. right-handed, +z-forward
# lidar (velo): ???
# GPS/IMU: ???