# @package _global_

defaults:
  - _self_
  - paths/paths_kitti
  - common

repo_root: ${repo_root}
data_root: ${data_root}
seq_num: ${seq_num}
output_dir: ${repo_root}/results/exp_hg_kitti_ts
vis: false
save_vis: true
gt_dir: ${repo_root}/results/gt_kitti

# --- experiment parameters --- #

# invert the direction of homography comp. (experimental, off)
invert_direction: false
# Whether to use a ground truth starting point 
# and adjust values to it (experimental, turn it off).
accumulate_values: false

# handle outliers during decomposition (if solutions are outside of criteria)
handle_outliers: true

# skip current update if hg. is invalid, filter will return its last estimation
skip_invalid_update: true

# filter

temporal_filter: SLERP  # KF / EKF / MEKF / SLERP
use_plane_ba   : false
ba_window_size : 5
fps: 10

# what to use to update the (Kalman) filter and get an estimation
filter_src: "normal"  # "normal" or "pitch"


# --- debug parameters --- #
plot_norm_candidates: false
single_frame: false
quicktest: false

# --- common parameters --- #
roi_img_src_size: ${roi_img_src_size}
roi: ${roi}